### ISSUE TITLE
where is the testset?

### ISSUE THREAD

**Issue by leileilin** [nightingal3/idiom-translation#1]

**Comment by nightingal3** [comment]
Hello,

You can find them under `https://github.com/nightingal3/idiom-translation/tree/main/metaphor-translation/data/test_sets_final` for each language. You can use `combined_test_set.csv` for each language, or this file that has test sets for all three languages: https://github.com/nightingal3/idiom-translation/blob/main/metaphor-translation/data/test_sets_final/combined_langs.csv
